[package]
resolver = "2"

[dependencies]
ra-common = { git = "https://github.com/AuthenticExecution/rust-sgx-remote-attestation.git" }
ra-enclave = { git = "https://github.com/AuthenticExecution/rust-sgx-remote-attestation.git" }
sgx-crypto = { git = "https://github.com/AuthenticExecution/rust-sgx-remote-attestation.git" }
